// Self-serve demo builder: scrape a hotel's own website, extract its facts and
// rooms into the SAME data shape the three built-in demo hotels use, then hand
// it to the shared engine + instructions. Fetch = Firecrawl (handles JS sites);
// extraction = OpenAI structured output (no Anthropic). Everything the agent
// then quotes is still MOCK — availability and rates are generated by engine.js.

const OPENAI_KEY = () => process.env.OPENAI_API_KEY;
const EXTRACT_MODEL = process.env.DEMO_EXTRACT_MODEL || "gpt-4o-mini";

// key pools (rotate on rate-limit / auth failure so one bad key never fails a build)
const uniq = (a) => [...new Set(a.map((s) => (s || "").trim()).filter(Boolean))];
const FC_KEYS = () => uniq([process.env.FIRECRAWL_API_KEY, ...(process.env.FIRECRAWL_API_KEY_POOL || "").split(",")]);
const APIFY_TOKENS = () => uniq([process.env.APIFY_TOKEN, ...(process.env.APIFY_TOKEN_POOL || "").split(",")]);

// links worth scraping beyond the homepage — where rooms/rates/facts actually live
const ENRICH_RE = /\/(rooms?|zimmer|suites?|accommodation|accommodations|chambres?|habitaciones?|camere|quartos|rates?|preise|prices?|tarifs|about|ueber-uns|ueber|our-hotel|hotel|amenities|facilities|dining|restaurant)(\/|\.|$|\?)/i;

const CURRENCY_SYMBOL = { USD: "$", CAD: "$", AUD: "$", NZD: "$", EUR: "€", GBP: "£", INR: "₹", JPY: "¥", CNY: "¥", CHF: "CHF", AED: "د.إ", ZAR: "R", BRL: "R$", MXN: "$", SGD: "$", THB: "฿", TRY: "₺", PLN: "zł", SEK: "kr", NOK: "kr", DKK: "kr" };
const COUNTRY_TZ = { india: "Asia/Kolkata", germany: "Europe/Berlin", canada: "America/Toronto", "united states": "America/New_York", usa: "America/New_York", "united kingdom": "Europe/London", uk: "Europe/London", france: "Europe/Paris", spain: "Europe/Madrid", italy: "Europe/Rome", netherlands: "Europe/Amsterdam", portugal: "Europe/Lisbon", japan: "Asia/Tokyo", china: "Asia/Shanghai", australia: "Australia/Sydney", "united arab emirates": "Asia/Dubai", uae: "Asia/Dubai", mexico: "America/Mexico_City", brazil: "America/Sao_Paulo", thailand: "Asia/Bangkok", turkey: "Europe/Istanbul", singapore: "Asia/Singapore", switzerland: "Europe/Zurich" };

// base nightly rate bands per currency for generated rates (demo only; used only
// when the scraped page carried no price). Keep roughly in-scale per currency so
// a generated rate never reads absurd (e.g. a KRW room in the hundreds).
const RATE_BAND = {
  USD: [180, 520], CAD: [190, 540], AUD: [190, 520], NZD: [200, 560], EUR: [95, 340], GBP: [90, 320], CHF: [160, 480],
  INR: [5000, 20000], JPY: [14000, 55000], CNY: [500, 2200], AED: [400, 1600], SAR: [500, 1800], SGD: [200, 600],
  THB: [2500, 9000], TRY: [2000, 8000], PLN: [350, 1200], SEK: [1500, 5000], NOK: [1500, 5000], DKK: [900, 3000],
  ZAR: [1500, 6000], BRL: [400, 1500], MXN: [1800, 6000], KRW: [150000, 500000], IDR: [800000, 3500000], HUF: [40000, 140000],
  default: [120, 420],
};

// ---- provider 1: Firecrawl (pool rotation + homepage + up to 2 enrich pages) ----
async function fcScrapeOne(url, key, withLinks) {
  try {
    const r = await fetch("https://api.firecrawl.dev/v2/scrape", {
      method: "POST",
      headers: { authorization: `Bearer ${key}`, "content-type": "application/json" },
      body: JSON.stringify({ url, formats: withLinks ? ["markdown", "links"] : ["markdown"], onlyMainContent: true, timeout: 25000 }),
      signal: AbortSignal.timeout(35_000),
    });
    if (!r.ok) return { retry: r.status === 401 || r.status === 402 || r.status === 429 };
    const j = await r.json();
    return { markdown: j.data?.markdown || "", title: j.data?.metadata?.title || "", links: j.data?.links || [] };
  } catch {
    return { retry: true };
  }
}

function pickEnrichUrls(links, base) {
  let host;
  try { host = new URL(base).hostname.replace(/^www\./, ""); } catch { return []; }
  const seen = new Set([base.replace(/\/$/, "")]);
  const out = [];
  for (const l of links || []) {
    if (typeof l !== "string") continue;
    let u;
    try { u = new URL(l, base); } catch { continue; }
    if (u.hostname.replace(/^www\./, "") !== host) continue;
    const clean = u.origin + u.pathname.replace(/\/$/, "");
    if (seen.has(clean) || !ENRICH_RE.test(u.pathname)) continue;
    seen.add(clean);
    out.push(clean);
  }
  // rooms pages first
  return out.sort((a, b) => (/(rooms?|zimmer|suite|chambre|habitacion|camere|quarto)/i.test(b) - /(rooms?|zimmer|suite|chambre|habitacion|camere|quarto)/i.test(a)));
}

async function firecrawlGather(url) {
  const keys = FC_KEYS();
  if (!keys.length) return null;
  let home = null, usedKey = null;
  for (const k of keys) {
    const res = await fcScrapeOne(url, k, true);
    if (res && res.markdown != null && !res.retry) { home = res; usedKey = k; break; }
    if (res && !res.retry) break; // a non-retryable failure won't improve with another key
  }
  if (!home || !(home.markdown || "").length) return null;
  let text = home.markdown, title = home.title;
  const extra = pickEnrichUrls(home.links, url).slice(0, 2);
  for (const u of extra) {
    const p = await fcScrapeOne(u, usedKey, false);
    if (p && p.markdown) text += "\n\n---\n\n" + p.markdown;
  }
  return { text: text.slice(0, 16000), title, provider: "firecrawl", pages: 1 + extra.length };
}

// ---- provider 2: Apify Website Content Crawler (independent backup; async+poll) ----
// Rotates the whole token pool so an exhausted free token (403 "hard limit")
// hands off to the next; wired-and-ready even if today's tokens are spent.
async function apifyStart(url) {
  for (const token of APIFY_TOKENS()) {
    try {
      const start = await fetch(`https://api.apify.com/v2/acts/apify~website-content-crawler/runs?token=${token}`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ startUrls: [{ url }], maxCrawlPages: 3, crawlerType: "playwright:adaptive", saveMarkdown: true, maxResults: 3 }),
        signal: AbortSignal.timeout(15_000),
      });
      if (start.ok) {
        const runId = (await start.json()).data?.id;
        if (runId) return { runId, token };
      } // 402/403/429 → try the next token
    } catch { /* try the next token */ }
  }
  return null;
}

async function apifyGather(url) {
  if (!APIFY_TOKENS().length) return null;
  try {
    const started = await apifyStart(url);
    if (!started) return null;
    const { runId, token } = started;
    // poll (bounded) until the run finishes
    const deadline = Date.now() + 85_000;
    let dataset = null;
    while (Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, 4000));
      const st = await fetch(`https://api.apify.com/v2/actor-runs/${runId}?token=${token}`, { signal: AbortSignal.timeout(12_000) });
      if (!st.ok) continue;
      const d = (await st.json()).data;
      if (d?.status === "SUCCEEDED") { dataset = d.defaultDatasetId; break; }
      if (["FAILED", "ABORTED", "TIMED-OUT"].includes(d?.status)) return null;
    }
    if (!dataset) return null;
    const items = await (await fetch(`https://api.apify.com/v2/datasets/${dataset}/items?token=${token}&clean=true&limit=3`, { signal: AbortSignal.timeout(15_000) })).json();
    if (!Array.isArray(items) || !items.length) return null;
    const text = items.map((it) => it.markdown || it.text || "").join("\n\n---\n\n").slice(0, 16000);
    if (text.length < 120) return null;
    return { text, title: items[0]?.metadata?.title || items[0]?.title || "", provider: "apify", pages: items.length };
  } catch {
    return null;
  }
}

// ---- provider 3: last-ditch plain fetch (server-rendered sites) ----
async function plainScrape(url) {
  try {
    const r = await fetch(url, { headers: { "user-agent": "Mozilla/5.0 SunnyDeskDemoBot" }, signal: AbortSignal.timeout(15_000) });
    if (!r.ok) return null;
    const html = await r.text();
    const title = (html.match(/<title[^>]*>([^<]+)<\/title>/i) || [])[1] || "";
    const text = html
      .replace(/<script[\s\S]*?<\/script>/gi, " ")
      .replace(/<style[\s\S]*?<\/style>/gi, " ")
      .replace(/<[^>]+>/g, " ")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, 9000);
    if (text.length < 120) return null;
    return { text, title, provider: "plain", pages: 1 };
  } catch {
    return null;
  }
}

/** The layered fetch: Firecrawl (multi-page) → Apify (independent backup) → plain
    fetch. Returns the first usable content, or null if every provider fails. */
async function gatherSiteContent(url) {
  const fc = await firecrawlGather(url);
  if (fc && fc.text.length > 150) return fc;
  const ap = await apifyGather(url);
  if (ap && ap.text.length > 150) return ap;
  const pf = await plainScrape(url);
  if (pf && pf.text.length > 120) return pf;
  return null;
}

const EXTRACT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    name: { type: "string" },
    city: { type: "string" },
    country: { type: "string" },
    currency: { type: "string", description: "ISO 4217 code (USD, EUR, INR, ...) — infer from country if the page doesn't say" },
    phone: { type: "string" },
    email: { type: "string" },
    address: { type: "string" },
    greeting: { type: "string", description: "The exact opening line the receptionist speaks, IN THE TARGET LANGUAGE, naming the hotel and the agent, ending with a short English offer if the language is not English." },
    vibe: { type: "string", description: "Two English sentences describing what the hotel feels like." },
    facts: {
      type: "object",
      additionalProperties: false,
      properties: {
        overview: { type: "string" }, breakfast: { type: "string" }, parking: { type: "string" },
        amenities: { type: "string" }, checkin_checkout: { type: "string" }, policies: { type: "string" },
        location: { type: "string" }, family: { type: "string" }, payment: { type: "string" },
      },
      required: ["overview", "breakfast", "parking", "amenities", "checkin_checkout", "policies", "location", "family", "payment"],
    },
    rooms: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          name: { type: "string" },
          flavor: { type: "string", description: "one warm English sentence" },
          beds: { type: "string" },
          size_sqm: { type: "integer", description: "0 if unknown" },
          approx_rate: { type: "integer", description: "nightly rate in the hotel's currency if the page shows one, else 0" },
          tier: { type: "string", enum: ["standard", "double", "suite", "family"] },
          features: { type: "array", items: { type: "string" } },
        },
        required: ["name", "flavor", "beds", "size_sqm", "approx_rate", "tier", "features"],
      },
    },
    local_tips: {
      type: "array",
      description: "6 real, plausible things to do near the hotel's city",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          name: { type: "string" },
          type: { type: "string", enum: ["sight", "food", "nature", "culture", "market", "activity"] },
          line: { type: "string" },
          hours: { type: "string" },
        },
        required: ["name", "type", "line", "hours"],
      },
    },
  },
  required: ["name", "city", "country", "currency", "phone", "email", "address", "greeting", "vibe", "facts", "rooms", "local_tips"],
};

async function openaiExtract({ text, title, url, languageName, agentName }) {
  const key = OPENAI_KEY();
  if (!key) return null;
  const sys = `You turn a hotel website's scraped text into structured data for a voice-agent DEMO.
Rules:
- Use ONLY what the page supports for facts, room names, and contact details. If a fact isn't on the page, write a short, safe, GENERIC-but-plausible sentence for that hotel type (never invent specific unverifiable claims like awards or star ratings).
- The receptionist agent will speak ${languageName}. Write "greeting" in ${languageName} (name the hotel and the agent "${agentName}"), and if ${languageName} is not English add a short "you're welcome to speak English too" style clause in English.
- "vibe" stays in English (it's prompt scaffolding, not spoken).
- Provide 3 or 4 rooms. If the page lists rooms, use them; otherwise infer a sensible set for this hotel type. Set approx_rate only if the page actually shows a price, else 0.
- local_tips: 6 real, well-known things to do near ${title || url}'s city.`;
  const user = `Hotel website: ${url}\nPage title: ${title}\n\nScraped content:\n${text.slice(0, 9000)}`;
  try {
    const r = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: { authorization: `Bearer ${key}`, "content-type": "application/json" },
      body: JSON.stringify({
        model: EXTRACT_MODEL,
        temperature: 0.4,
        messages: [{ role: "system", content: sys }, { role: "user", content: user }],
        response_format: { type: "json_schema", json_schema: { name: "hotel", strict: true, schema: EXTRACT_SCHEMA } },
      }),
      signal: AbortSignal.timeout(40_000),
    });
    if (!r.ok) { console.warn(`[scrape] extract ${r.status}: ${(await r.text()).slice(0, 200)}`); return null; }
    const j = await r.json();
    return JSON.parse(j.choices[0].message.content);
  } catch (e) {
    console.warn(`[scrape] extract error: ${e.message}`);
    return null;
  }
}

// ---- helpers ----
const kebab = (s) => String(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40) || "room";
function hashInt(s) { let h = 2166136261; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return (h >>> 0) % 100000; }
const roundRate = (cur, n) => (cur === "INR" || cur === "JPY" ? Math.round(n / 50) * 50 : Math.round(n / 5) * 5);
const TIER_ADULTS = { standard: 2, double: 2, suite: 3, family: 4 };
const TIER_CHILD = { standard: 0, double: 1, suite: 1, family: 3 };
const TIER_SQM = { standard: 20, double: 26, suite: 44, family: 40 };

// The voices worth offering. OpenAI's docs: "For best quality, use marin or
// cedar" — those two are the only current-generation Realtime voices; coral is
// the best of the older tier. Gender is *perceived*, not official, but a voice
// that fights the agent's name is one of the strongest robot tells.
export const VOICES = [
  { id: "marin", label: "Marin — bright, natural (female)", tier: "best" },
  { id: "cedar", label: "Cedar — warm, grounded (male)", tier: "best" },
  { id: "coral", label: "Coral — warm, friendly (female)", tier: "good" },
];

function normalize(raw, { url, primaryLanguage, languageName, agentName, voice }) {
  // accept ANY valid ISO 4217 code (uppercased), not just ones we have a symbol
  // for; fall back to EUR only when it isn't a 3-letter code at all.
  const rawCur = String(raw.currency || "").toUpperCase().trim();
  const cur = /^[A-Z]{3}$/.test(rawCur) ? rawCur : "EUR";
  const band = RATE_BAND[cur] || RATE_BAND.default;
  const host = (() => { try { return new URL(url).hostname.replace(/^www\./, ""); } catch { return "hotel"; } })();
  const name = (raw.name || raw.title || host.split(".")[0]).trim();
  const seed = hashInt(name + cur);

  let rooms = Array.isArray(raw.rooms) ? raw.rooms.slice(0, 4) : [];
  if (rooms.length < 2) {
    rooms = [
      { name: "Standard Room", flavor: "A comfortable, quiet room with everything you need for a good night's rest.", beds: "1 double bed", tier: "double", size_sqm: 0, approx_rate: 0, features: ["Free Wi-Fi", "Ensuite bathroom", "Tea and coffee"] },
      { name: "Superior Room", flavor: "A brighter, roomier stay with a little more space to relax.", beds: "1 queen bed", tier: "double", size_sqm: 0, approx_rate: 0, features: ["Free Wi-Fi", "Seating area", "City view"] },
      { name: "Suite", flavor: "A spacious suite with a separate sitting area for a special stay.", beds: "1 king bed plus sofa", tier: "suite", size_sqm: 0, approx_rate: 0, features: ["Separate lounge", "Bathtub", "Premium view"] },
      { name: "Family Room", flavor: "Room for the whole family, with space for the children to settle in.", beds: "1 double plus 2 singles", tier: "family", size_sqm: 0, approx_rate: 0, features: ["Sleeps four", "Extra space", "Family-friendly"] },
    ];
  }
  const rankOrder = { standard: 0, double: 1, suite: 2, family: 3 };
  rooms = rooms.map((r, i) => {
    const tier = ["standard", "double", "suite", "family"].includes(r.tier) ? r.tier : "double";
    const rate = r.approx_rate && r.approx_rate > 0 ? roundRate(cur, r.approx_rate) : roundRate(cur, band[0] + ((band[1] - band[0]) * (rankOrder[tier] / 3)));
    return {
      id: kebab(r.name) + "-" + i,
      name: r.name || `Room ${i + 1}`,
      flavor: r.flavor || "A comfortable room for your stay.",
      sizeSqm: r.size_sqm && r.size_sqm > 0 ? r.size_sqm : TIER_SQM[tier],
      beds: r.beds || "1 double bed",
      maxAdults: TIER_ADULTS[tier],
      maxChildren: TIER_CHILD[tier],
      baseRate: rate,
      count: 3 + (hashInt(name + r.name + i) % 6),
      features: Array.isArray(r.features) && r.features.length ? r.features.slice(0, 5) : ["Free Wi-Fi"],
    };
  });

  const facts = raw.facts || {};
  const factOr = (k, d) => (facts[k] && facts[k].length > 3 ? facts[k] : d);
  const country = raw.country || "";
  const tz = COUNTRY_TZ[country.toLowerCase()] || "Europe/London";
  const refPrefix = (name.replace(/[^A-Za-z]/g, "").toUpperCase() + "XXX").slice(0, 3);

  let tips = Array.isArray(raw.local_tips) ? raw.local_tips.filter((t) => t && t.name).slice(0, 6) : [];
  if (!tips.length) tips = [{ name: `Explore ${raw.city || "the area"}`, type: "activity", line: "Ask the front desk for a walking route to the best nearby sights and food.", hours: "Anytime" }];

  return {
    id: "custom",
    custom: true,
    // the visitor picks the voice (never hash-assigned — a hash can hand a
    // female-named agent a male-perceived voice, which is a loud uncanny tell)
    voice: VOICES.some((v) => v.id === voice) ? voice : "marin",
    name,
    city: raw.city || host,
    country,
    currency: cur,
    currencySymbol: CURRENCY_SYMBOL[cur] || cur,
    primaryLanguage,
    languageName,
    agentName,
    timezone: tz,
    phone: raw.phone || "(front desk — demo hotel, number not dialable)",
    email: raw.email || "frontdesk@example.com",
    address: raw.address || raw.city || "",
    checkin: "15:00",
    checkout: "11:00",
    greeting: raw.greeting || `Hello, welcome to ${name} — this is ${agentName}, how can I help you today?`,
    vibe: raw.vibe || `${name} is a welcoming hotel in ${raw.city || "town"}.`,
    facts: {
      overview: factOr("overview", `${name} is a hotel in ${raw.city || "town"}.`),
      rooms: `${name} offers ${rooms.map((r) => r.name).join(", ")}.`,
      breakfast: factOr("breakfast", "Breakfast is available each morning; ask the front desk for times and what's included."),
      checkin_checkout: factOr("checkin_checkout", "Check-in is from 3:00 PM and check-out is by 11:00 AM; early check-in and late check-out can be arranged when rooms allow."),
      parking: factOr("parking", "Please ask the front desk about parking options near the hotel."),
      amenities: factOr("amenities", "The hotel offers free Wi-Fi and helpful front-desk service; ask about other amenities."),
      policies: factOr("policies", "Cancellation and house policies are confirmed at booking; the hotel is non-smoking indoors."),
      location: factOr("location", `The hotel is located in ${raw.city || "town"}; the front desk can help with directions.`),
      contact: `You can reach the front desk at ${raw.phone || "the number on the hotel's website"}${raw.email ? " or " + raw.email : ""}.`,
      family: factOr("family", "Families are welcome; ask the front desk about cots, extra beds, and family rooms."),
      payment: factOr("payment", "Major cards are accepted; a card holds the booking and payment is settled at the hotel."),
    },
    rooms,
    seasons: [],
    weekendMult: 1.15,
    demandSeed: seed % 90 + 5,
    refPrefix,
    localTips: tips.map((t) => ({ name: t.name, type: t.type || "activity", line: t.line || "", hours: t.hours || "" })),
  };
}

/** Build a demo hotel object from a live URL. Never throws — returns a usable
    hotel plus `source` (scraped/generated) and the `provider` that won, so the
    UI can be honest about a thin read and logs show which layer served it. */
export async function buildHotelFromUrl({ url, primaryLanguage, languageName, agentName, voice }) {
  const content = await gatherSiteContent(url);
  let extracted = null, source = "generated";
  const provider = content?.provider || "none";
  if (content && content.text.length > 80) {
    extracted = await openaiExtract({ text: content.text, title: content.title, url, languageName, agentName });
    if (extracted) source = "scraped";
  }
  if (content) console.log(`[scrape] ${url} → ${provider} (${content.pages} page${content.pages > 1 ? "s" : ""}, ${content.text.length} chars) → ${source}`);
  else console.log(`[scrape] ${url} → no content from any provider → generated`);
  const raw = extracted || { title: content?.title || "", city: "", country: "", rooms: [] };
  const hotel = normalize(raw, { url, primaryLanguage, languageName, agentName, voice });
  return { hotel, source, provider };
}
